config/routes.rb
Rails.application.routes.draw do
  root 'books#index'

  resources :users
  resources :sessions
  namespace :admin do
    resources :books do
      collection do
        post :book_update
      end
    end
  end
  
  resources :borrows
  resources :books do
    member do
      post :add_to_borrow
      post :return_book
    end
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
end

app/models/borrow.rb
class Borrow < ApplicationRecord
  has_many :borrow_items
  has_many :books, through: :borrow_items, source: :book

  def add_book_to_borrow(book)
    bi = borrow_items.build
    bi.book = book
    bi.quantity = 1
    bi.save
  end
end

app/models/borrow_item.rb
class BorrowItem < ApplicationRecord
  belongs_to :book
  belongs_to :borrow
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!
  attr_accessor :password, :password_confirmation

  validates_presence_of :email, message: "邮箱不能为空"
  validates :email, uniqueness: true
  validates_presence_of :password, message: "密码不能为空",
    if: :need_validate_password
  validates_presence_of :password_confirmation, message: "密码确认不能为空",
    if: :need_validate_password
  validates_confirmation_of :password, message: "密码不一致",
    if: :need_validate_password
  validates_length_of :password, message: "密码最短6位",
    minimum: 6,
    if: :need_validate_password

  private

  def need_validate_password
    self.new_record? ||
      (!self.password.nil? or !self.password_confirmation.nil?)
  end
end

app/controllers/admin/books_controller.rb
class Admin::BooksController < ApplicationController
  layout "admin"
  before_action :admin_required

  def index
    @books = Book.all
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)

    if @book.save
      #查询单个数据必须传递参数实现检索定位，例如@book
      redirect_to book_path(@book)
    else
      render "new"
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])

    if @book.update(book_params)
      #查询某数据表所有数据，可以省略传递参数
      redirect_to admin_books_path
    else
      render "edit"
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy

    redirect_to admin_books_path
  end

  def book_update
    @book = Book.find(params[:id])
    if @book.book_state == "上架"
      @book.update(book_state: "下架")
      flash[:error] = "下架成功"
    else
      @book.update(book_state: "上架")
      flash[:error] = "上架成功"
    end
    redirect_to admin_books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :text, :book_stock, :book_state)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def admin_required
    if !current_user.present?
      redirect_to '/' , alert: "你不是管理员"
    end
  end

  helper_method :current_borrow

  def current_borrow
    @current_borrow ||= find_borrow
  end

  private

  def find_borrow
    borrow = Borrow.find_by(id: session[:borrow_id])

    if borrow.blank?
      borrow = Borrow.create
    end

    session[:borrow_id] = borrow.id
    return borrow
  end  
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
  end

  def show
    @book = Book.find(params[:id])
  end

  def add_to_borrow
    @book = Book.find(params[:id])
    if !current_borrow.books.include?(@book)
      current_borrow.add_book_to_borrow(@book)
      @book.book_stock = @book.book_stock - 1
      @book.save

      flash[:notice] = "成功将 #{@book.title} 加入借书单"
    else
      flash[:waning] = "你的借书单已有本书"
    end
    redirect_to books_path
  end

  def return_book
    @borrow_item = BorrowItem.find(params[:id])
    if @borrow_item.destroy
      @borrow_item.book.book_stock = @borrow_item.book.book_stock + 1
      @borrow_item.book.save
      redirect_to borrows_path
      flash[:notice] = "还书成功"
    else
      flash[:error] = "还书失败"
    end
  end
end

app/controllers/borrows_controller.rb
class BorrowsController < ApplicationController
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :auth_user, except: [:destroy]

  def new
  end

  def create
    #login是sorcery的登录方法
    if user = login(params[:email], params[:password])
      flash[:notice] = '登陆成功'
      redirect_to root_path
    else
      flash[:notice] = "邮箱或者密码错误"
      redirect_to new_session_path
    end
  end

  def destroy
    #logout是sorcery的退出方法
    logout
    flash[:notice] = "退出登陆"
    redirect_to root_path
  end

  private

  def auth_user
    #logged_in?是sorcery的判断登录方法
    if logged_in?
      redirect_to root_path
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  #用户注册
  def create
    @user = User.new(params.require(:user)
      .permit(:email, :password, :password_confirmation))

    if @user.save
      flash[:notice] = '注册成功，请登录'
      redirect_to new_session_path
    else
      render action: :new
    end
  end

  #用户密码修改
  def change_password
    if current_user.valid_password?(params[:old_password])
      current_user.password_confirmation = params[:password_confirmation]

      if current_user.change_password!(params[:password])
        render json: {status: 'ok', msg: '密码修改成功'}
      else
        render json: {status: 'error', msg: current_user.errors.messages.values.flatten}
      end
    else
      render json: {status: 'error', msg: '旧密码不正确'}
    end
  end

  #用户发送忘记密码邮件,这里需要对邮件进行配置
  def send_forget_password_email
    @user = User.find_by(email: params[:email])
    if @user
      @user.deliver_reset_password_instructions!
      render json: {status: 'ok', msg: "重置密码的链接已发送到上面的邮箱"}
    else
      render json: {status: 'error', msg: '指定邮箱不存在'}
    end
  end

  #密码重置
  def reset_password
    @user = User.load_from_reset_password_token(params[:token])
    if @user
      @user.password_confirmation = params[:password_confirmation]
      if @user.change_password!(params[:password])
        render json: {status: 'ok', msg: '密码修改成功'}
      else
        render json: {status: 'error', msg: @user.errors.messages.values.flatten}
      end
    else
      render json: {status: 'error', msg: 'token不正确或者已过期'}
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    #flash[:notice] = "早安！你好！"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flashes_helper.rb
module FlashesHelper
  FLASH_CLASSES = { alert: "danger", notice: "success", warning: "warning"}.freeze

  def flash_class(key)
    FLASH_CLASSES.fetch key.to_sym, key
  end

  def user_facing_flashes
    flash.to_hash.slice "alert", "notice","warning"
  end
end

app/views/admin/books/edit.html.erb
<h1>图书修改</h1>
<%= form_for [:admin, @book] do |f| %>
  <p>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :text %>
    <%= f.text_area :text %>
  </p>

  <p>
    <%= f.label "库存" %>
    <%= f.number_field :book_stock %>
  </p>

  <p>
    <%= f.label "状态" %> </br>
    <%= f.select 'book_state', options_for_select(['上架', '下架']) %>
  </p>

  <p>
    <%= f.submit "提交"%>
  </p>
<% end %>

app/views/admin/books/index.html.erb
<h1>图书馆后台</h1>
<%=flash[:error]%>
<%=flash[:waning]%>
<%=flash[:notice]%>
<p>
  <%= link_to "新书上架", new_admin_book_path %>
</p>

<table class="table table-bordered table-hover">
  <tr class="text-info">
    <th>书名</th>
    <th>简介</th>
    <th>库存</th>
    <th>状态</th>
    <th>操作</th>
  </tr>
  <% @books.each do |book| %>
    <tr>
      <td><%= link_to "#{book.title}" , book_path(book) %></td>
      <td><%= book.text %></td>
      <td><%= book.book_stock %></td>
      <td><%= link_to("#{book.book_state}", book_update_admin_books_path(:id => book.id),
                      method: :post , :class => "btn btn-xs btn-default") %></td>
      <td>
        <%= link_to "显示", book_path(book) %><span style="margin-left: 5px">|</span>
        <%= link_to "编辑", edit_admin_book_path(book) %><span style="margin-left: 5px">|</span>
        <%= link_to "删除", admin_book_path(book),
            method: :delete, data: { confirm: "确定删除本书？"} %>
      </td>
    </tr>
  <% end %>
</table>

app/views/admin/books/new.html.erb
<h1>新书上架</h1>
<%= form_for [:admin, @book] do |f| %>
  <p>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :text %>
    <%= f.text_area :text %>
  </p>

  <p>
    <%= f.label "库存" %> 
    <%= f.number_field :book_stock %>
  </p>

  <p>
    <%= f.label "状态" %> </br>
    <%= f.select 'book_state', options_for_select(['上架', '下架']) %>
  </p>

  <p>
    <%= f.submit "提交"%>
  </p>
<% end %>

app/views/books/index.html.erb
<h1>图书首页</h1>
<%=flash[:error]%>
<%=flash[:waning]%>
<%=flash[:notice]%>

<table class="table table-bordered table-hover">
  <tr class="text-info">
    <th>书名</th>
    <th>简介</th>
    <th>库存</th>
    <th>操作</th>
  </tr>
  <% @books.each do |book| %>
    <tr>
      <td><%= link_to "#{book.title}", book_path(book) %></td>
      <td><%= book.text %></td>
      <td><%= book.book_stock %></td>
      <td>
          <%= link_to '显示', book_path(book) %>
          <%if current_user%>
              <span style="margin-left: 5px;">|</span>
              <%= link_to '借阅', add_to_borrow_book_path(:id => book.id), :method => :post, :class => "btn btn-primary btn-lg btn-danger" %>
          <%end%>
      </td>
    </tr>
  <% end %>
</table>

app/views/books/show.html.erb
<h1>图书简介</h1>
<p>
  <strong>书名:</strong>
  <%= @book.title %>
</p>
<p>
  <strong>简介:</strong>
  <%= @book.text %>
</p>
<p>
  <strong>库存:</strong>
  <%= @book.book_stock %>
</p>

app/views/borrows/index.html.erb
<h1>借书单</h1>
<%=flash[:error]%>
<%=flash[:waning]%>
<%=flash[:notice]%>
<table class="table table-bordered table-hover">
  <tr class="text-info">
    <th>书名</th>
    <th>简介</th>
    <th>库存</th>
    <th>操作</th>
  </tr>
  <% current_borrow.borrow_items.each do |borrow_item| %>
  <tr>
    <th><%= borrow_item.book.title %></th>
    <th><%= borrow_item.book.text %></th>
    <th><%= borrow_item.book.book_stock %></th>
    <th><%= link_to '还书', return_book_book_path(:id => borrow_item.id),
            :method => :post, :class => "btn btn-primary btn-lg btn-danger" %></th>
  </tr>
  <% end %>
</table>

app/views/common/_flashes.html.erb
<% if flash.any? %>
  <% user_facing_flashes.each do |key, value| %>
    <div class="alert alert-dismissable alert-<%= flash_class(key) %>">
      <button class="close" data-dismiss="alert">×</button>
      <%= value %>
    </div>
  <% end %>
<% end %>

app/views/common/_footer.html.erb
<footer class="container-fluid navbar-fixed-bottom" style="margin-top: 100px;">
    <p class="text-center">图书管理系统
        <br>Planck1043
    </p>
</footer>

app/views/common/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <a class="navbar-brand" href="/">图书管理系统</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
              <li>
                <%= link_to borrows_path do  %>
                   借书单 <i class="fa fa-shopping-borrow"> </i> ( <%= current_borrow.books.count %> )
                <% end %>
              </li>
              <% if !current_user %>
                <li><%= link_to("注册", new_user_path) %> </li>
                <!-- 在 rails 中 "link_to" 是 "<a>" 的封装 -->
                <li><%= link_to("登入", new_session_path) %></li>
              <% else %>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                      Hi!, <%= current_user.email %>
                      <b class="caret"></b>
                  </a>
                  <ul>
                    <li><%= link_to "后台", admin_books_path %></li>
                    <li> <%= link_to("登出", session_path(session),
                            method: :delete, data: { confirm: '确认退出吗?' } ) %> </li>
                  </ul>
                </li>
              <% end %>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
</nav>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>图书馆 后台</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <%= render "common/navbar" %>
    <div class="row">
      <div class="col-md-2">
        <ul class="nav nav-pills nav-stacked" style="max-width: 300px;">
          <li> <%= link_to("图书", admin_books_path) %> </li>
        </ul>
      </div>
      <div class="col-md-10">
        <%= yield %>
      </div>
      <%= render "common/footer" %>
    </div>
  </div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Library01</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid">
      <%= render "common/navbar" %>
      <%#= render "common/flashes" %>
      <%= yield %>
    </div>
    <%= render "common/footer" %>
  </body>
</html>

app/views/users/new.html.erb
<h1>用户注册</h1>
<div>
  <% unless @user.errors.empty? %>
    <ul>
      <% @user.errors.messages.values.flatten.each do |error| %>
        <li><%= error %></li>
      <% end -%>
    </ul>
  <% end -%>
</div>
<%= form_for :user, url: users_path, method: :post, html: { class: 'form-horizontal', id: "user_form"} do |f| %>
  <div class="form-group">
    <div class="col-lg-12">邮箱 *</div>
    <div class="col-lg-12">
      <%= f.text_field :email, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-lg-12">密码 *</div>
    <div class="col-lg-12">
      <%= f.password_field :password, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-lg-12">密码确认 *</div>
    <div class="col-lg-12">
      <%= f.password_field :password_confirmation, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-lg-12">
      <div class="text-center">
        <a href="<%= new_session_path %>">登录</a>
      </div>
    </div>
  </div>
  <div class="form-group">
    <div class="col-lg-12">
      <input type="submit" name="create_user_submit" value="创建账户" class="col-xs-12 btn btn-primary">
    </div>
  </div>
<% end %>

app/views/welcome/index.html.erb
<h1>Hello World</h1>